# Generated by Django 4.2.6 on 2023-10-28 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField(verbose_name='题目')),
            ],
        ),
        migrations.CreateModel(
            name='Selections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select', models.TextField(verbose_name='选项')),
                ('judge', models.BooleanField(default=True, verbose_name='正误')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.topic')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.TextField(verbose_name='知识点')),
                ('video', models.FileField(blank=True, null=True, upload_to='video', verbose_name='视频')),
                ('select', models.ManyToManyField(to='master.selections')),
            ],
        ),
    ]
