# Generated by Django 4.2.6 on 2023-10-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgepoints',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='链接'),
        ),
    ]
