# Generated by Django 4.2.6 on 2023-10-29 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_selections_judge'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='附图'),
        ),
    ]
