# Generated by Django 4.2.6 on 2023-10-29 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_topic_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgepoints',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='文字讲解'),
        ),
    ]
