# Generated by Django 4.2.6 on 2023-10-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_knowledgepoints_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='image', verbose_name='附图'),
        ),
    ]
