# Generated by Django 4.2.6 on 2023-11-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_alter_topic_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgepoints',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='image', verbose_name='图形解释'),
        ),
    ]
