# Generated by Django 4.2.6 on 2023-11-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_knowledgepoints_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='selections',
            name='explain',
            field=models.TextField(default='无', verbose_name='选项讲解'),
        ),
    ]
