# Generated by Django 4.2.6 on 2023-11-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_selections_explain'),
    ]

    operations = [
        migrations.AddField(
            model_name='selections',
            name='select2',
            field=models.ImageField(blank=True, null=True, upload_to='image', verbose_name='图片选项'),
        ),
    ]
