# Generated by Django 4.2.6 on 2023-11-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_selections_select2'),
    ]

    operations = [
        migrations.AddField(
            model_name='selections',
            name='fill',
            field=models.TextField(blank=True, null=True, verbose_name='填空正确答案'),
        ),
        migrations.AddField(
            model_name='topic',
            name='type',
            field=models.CharField(default='s', max_length=10, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='selections',
            name='judge',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='选择正误'),
        ),
    ]
