# Generated by Django 4.2.6 on 2023-11-19 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=11, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=21, verbose_name='密码')),
                ('phonenum', models.CharField(max_length=11, verbose_name='手机号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('edited_time', models.DateTimeField(auto_now=True, verbose_name='最近修改时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
            ],
        ),
        migrations.CreateModel(
            name='WrongQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrong_selectid', models.IntegerField(verbose_name='错误选项id')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('edited_time', models.DateTimeField(auto_now=True, verbose_name='最近修改时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('level_mastery', models.IntegerField(default=1, verbose_name='掌握程度')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userinformation')),
            ],
        ),
    ]
