# Generated by Django 4.2.6 on 2023-11-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='password',
            field=models.CharField(max_length=32, verbose_name='密码'),
        ),
    ]
