# Generated by Django 4.2.6 on 2023-11-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userinformation_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wrongquestion',
            name='wrong_selectid',
        ),
        migrations.AddField(
            model_name='wrongquestion',
            name='wrong_pointid',
            field=models.IntegerField(default=0, verbose_name='错误知识点id'),
        ),
    ]
