# Generated by Django 4.2.6 on 2023-11-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_wrongquestion_wrong_selectid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrongquestion',
            name='wrong_pointid',
            field=models.IntegerField(default=0, unique=True, verbose_name='错误知识点id'),
        ),
    ]
