# Generated by Django 4.2.6 on 2023-11-20 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0012_knowledgepoints_science_education_edition'),
        ('user', '0004_alter_wrongquestion_wrong_pointid'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrongquestion',
            name='point',
            field=models.OneToOneField(default=19, on_delete=django.db.models.deletion.CASCADE, to='master.knowledgepoints'),
            preserve_default=False,
        ),
    ]
